### ISSUE TITLE
Loader not working on server side rendering

### ISSUE THREAD

**Issue by nicktz1408** [henrykuzmick/react-skeleton-loader#6]
Hi guys,
I am trying to use the loader on my react project. When I add them on the render method of a react class, an error is triggered, which says that the window is defined. This is happened because I am using server-side rendering (and specifically the next.js library) and the code on render is being executed on the server rather than the browser (where window is defined).

Is there any way to solve this?
Any help is appreciated! Thanks!

**Comment by tchalvak** [comment]
Yes, I have the same problem when building a static site render in react/gatsbyjs. The code gets built in an environment without a global window, and causes the build to fail. It forced me to remove the skeletons from my has-a-window site side because I need to build my site.

Would you be open to a PR for making a fix for this?

**Comment by henrykuzmick** [comment]
Hey! PRs super welcome, closing this in favor of #3
